# Generated by Django 5.0.1 on 2024-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabe',
            field=models.BooleanField(default=True),
        ),
    ]
