# Generated by Django 5.0.1 on 2024-01-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_availabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='one_styl.png', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
