# Generated by Django 3.2 on 2024-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(to='main.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
