# Generated by Django 3.2 on 2024-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
