# Generated by Django 5.0 on 2024-02-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
