# Generated by Django 5.0 on 2024-02-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://www.ruckmaul.com/content/images/thumbs/default-image_4000.png'),
        ),
    ]
